[package]
name = "icc-capability-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
icc-error = { path = "../icc-error" }
icc-rights = { path = "../icc-rights" }
icc-types = { path = "../icc-types" }

[lints]
workspace = true
