[package]
name = "icc-identity-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
icc-crypto-api = { path = "../../crypto/icc-crypto-api" }
icc-error = { path = "../icc-error" }
icc-platform-api = { path = "../../ports/icc-platform-api" }
icc-types = { path = "../icc-types" }

[lints]
workspace = true
